#!/usr/bin/expect --
set username [lindex $argv 0]
set password [lindex $argv 1]
set target [lindex $argv 2]
spawn vagrant ssh $target
expect "$ "
send "sudo -i\n"
expect "# "
send "useradd $username\n"
expect "# "
send "passwd $username\n"
expect "New password: "
send "$password\n"
expect "Retype new password: "
send "$password\n"
expect "# "
send "exit\n"
expect "$ "
send "exit\n"
interact
